// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAbLf9zDlro3w48JsDRQwuQ4fXSsuiGjc',
    appId: '1:658567876746:web:bb1e2551b3b8809949dd73',
    messagingSenderId: '658567876746',
    projectId: 'notesapp-7c256',
    authDomain: 'notesapp-7c256.firebaseapp.com',
    storageBucket: 'notesapp-7c256.firebasestorage.app',
    measurementId: 'G-E9JKEBRPTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU_T4B3cm9LWlRy6fxeG7PKAWHMKH1pGU',
    appId: '1:658567876746:android:df350c6204ad322a49dd73',
    messagingSenderId: '658567876746',
    projectId: 'notesapp-7c256',
    storageBucket: 'notesapp-7c256.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArPlVtglzZY0NqlOk47jljFb_pugMDTVo',
    appId: '1:658567876746:ios:82ca07d22b52a0be49dd73',
    messagingSenderId: '658567876746',
    projectId: 'notesapp-7c256',
    storageBucket: 'notesapp-7c256.firebasestorage.app',
    iosBundleId: 'com.example.notesApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArPlVtglzZY0NqlOk47jljFb_pugMDTVo',
    appId: '1:658567876746:ios:82ca07d22b52a0be49dd73',
    messagingSenderId: '658567876746',
    projectId: 'notesapp-7c256',
    storageBucket: 'notesapp-7c256.firebasestorage.app',
    iosBundleId: 'com.example.notesApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAbLf9zDlro3w48JsDRQwuQ4fXSsuiGjc',
    appId: '1:658567876746:web:0cd7ab518a0b220f49dd73',
    messagingSenderId: '658567876746',
    projectId: 'notesapp-7c256',
    authDomain: 'notesapp-7c256.firebaseapp.com',
    storageBucket: 'notesapp-7c256.firebasestorage.app',
    measurementId: 'G-NWD2MSPVY6',
  );
}
